---
- name: Install needed package
  apt: name="{{ common_pkgs }}" state=present update_cache=yes

- name: Install pipenv
  pip: name=pipenv state=latest

- name: Change login shell to fish
  command: chsh -s /usr/bin/fish vagrant
  tags: chsh
