---
- name: Install needed package
  apt: name="{{ common_pkgs }}" state=present update_cache=yes

- name: Install pipenv
  pip: name=pipenv state=latest

- name: Change login shell to fish
  command: chsh -s /usr/bin/fish vagrant

- name: Copy a config of tmux
  copy:
    src: ../files/.tmux.conf
    dest: ~/.tmux.conf
  become: vagrant

- name: Download my .emacs.d
  git:
    repo: https://github.com/owlinux1000/.emacs.d
    dest: ~/.emacs.d
  become: vagrant
  tags: emacs
    
